### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by apjanke** [apjanke/octave-testify#45]
The `test` function's code has some issues:

* The main function is several hundred lines long.
* Logic for parsing tests, running tests, and tracking results is interleaved across the whole function.
* All variables are prefixed with "__", hurting readability.
* It uses local functions, which can't be called directly, so they're hard to test.
* Results tracking is handled by seven or eight separate local variables.
* It uses `eval` logic with generated temporary function strings, which is a little hard to follow.

Same goes for `runtests`, to a lesser extent.

Refactor the code to address this.

### TODO

* [x] Factor out test-running implementation to objects
* [x] Test results summary in `runtests2`
* [ ] <strike>Give `runtests2` log file handling (for the lower-level `test` output)</strike>
* [x] More sophisticated input parsing for runtests2, for multiple targets, logging options, etc.
* [x] Have `__run_test_suite__` use runtest2's summary output

**Comment by apjanke** [comment]
I'm deferring logging to a separate issue https://github.com/apjanke/octave-testify/issues/56 because it's a more complicated topic and doesn't block the refactoring itself.

**Comment by apjanke** [comment]
I'm happy with the refactoring now. Moved `test2_refactor` and `runtests2_refactor` back to `test2` and `runtests2` in https://github.com/apjanke/octave-testify/commit/91d8fe76e71a11cbf1027283400f9b33a15b23ec.
